### ISSUE TITLE
Blocking plugin updates on startup

### ISSUE THREAD

**Issue by provsalt** [KnownUnown/Sheep#17]
Add a auto updater function where you can choose to auto update poggit plugin that are being released
Something like
Auto-update-plugins "false" on defult so it might not mess with more bigger servers which don't want bugs can have it off
Only runs at startup so it enables sheep first and check for updates if there are it will start downloading the new version and overwrite the old phar
after updates it will start loading all plugins

**Comment by tnytown** [comment]
Interesting idea. I'm not sure exactly how this would be achieved. This would require Sheep to effectively halt server startup while it checks for updates and downloads them, which cause problems. The current update mechanism is somewhat reliable, this feature would simply shift the plugin update check time to startup. May I ask if you have a specific use case for this?
